#!/bin/sh
#set -xv

FILES=$*

CAT=${CAT:-cat}
CPP=${CPP:-cpp}
SED=${SED:-sed}
HEXDUMP=${HEXDUMP:-hexdump}

USE_CPP=${USE_CPP:-yes}
FILTER_TO=${FILTER_TO:-}
FILTER_FROM=${FILTER_FROM:-}
USE_HEX=${USE_HEX:-yes}
HEXPAD=${HEXPAD:-16}
HEXNULL=${HEXNULL:-yes}
INTRO=${INTRO:-}
OUTRO=${OUTRO:-}

[ -n "${INTRO}" ] && echo "${INTRO}"

for f in ${FILES} ; do

  ( if [ "${USE_CPP}" = "yes" ] ; then
      ${CPP} ${CPPFLAGS} ${f}
    else
      ${CAT} ${f}
  fi ) | \
  ( if [ -n "${FILTER_TO}" ] ; then
      ${SED} -e "1,/${FILTER_TO}/d"
    else
      ${CAT}
  fi ) | \
  ( if [ -n "${FILTER_FROM}" ] ; then
      ${SED} -e "/${FILTER_FROM}/,\$d"
    else
      ${CAT}
  fi ) | \
  ( if [ "${USE_HEX}" = "yes" ] ; then
    ${HEXDUMP} -v -e "${HEXPAD}/1 \"0x%02x, \" \"\\n\"" | \
    ( if [ -n "${HEXPAD}" ] ; then ${SED} -e "s/0x  ,/0x00,/g" ; else ${CAT} ; fi ) | \
    ( if [ "${HEXNULL}" = "yes" ] ; then ${SED} -e "\$s/\$/ 0x00/" ; else ${CAT} ; fi )
  else
    ${SED} -e 's/"/\\"/g' -e 's/\\n/\\\\n/g' -e 's/^/\"/' -e 's/$/\\n\"/'
  fi ) | \
  ${CAT}

done

[ -n "${OUTRO}" ] && echo "${OUTRO}"

exit 0
